In [40]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
import re

In [41]:
df = pd.read_csv('test.csv')
dft = pd.read_csv('todascenario2Mileage.csv')

In [42]:
dft

,mileage_group,id_mileage_group,id_transmissao,transmission_type,body_type,id_body_type,modelo,id_modelos,marca,id_categoria_marca,...,id_fuel_type,kms_driven,kms_group,id_kms_group,max_power,max_power_group,id_max_power_group,owner_type,id_owner_type,resale_price_Lakh
0,10k-30k km,0.019654,0.131359,Manual,Hatchback,0.364112,Tiago XZ Plus,3.086522,Tata,0.073531,...,0.180334,30910.0,Até 50.000 km,0.364786,83.8,0-100 bhp,0.206644,First Owner,0.150465,5.66
1,10k-30k km,0.019654,0.131359,Manual,SUV,0.598869,WR-V i-VTEC VX,2.403638,Honda,0.073531,...,0.180334,48089.0,Até 50.000 km,0.364786,88.7,0-100 bhp,0.206644,Third Owner,1.365236,6.64
2,10k-30k km,0.019654,0.131359,Manual,Sedan,0.578053,City i VTEC SV,2.583846,Honda,0.073531,...,0.180334,51000.0,50.000 km a 150.000 km,0.255059,117.3,100-200 bhp,0.446040,Second Owner,0.620328,5.65
3,10k-30k km,0.019654,0.583102,Automatic,SUV,0.598869,New Safari XZA Plus Adventure Edition AT BSVI,3.650793,Tata,0.073531,...,0.514919,30000.0,Até 50.000 km,0.364786,167.6,100-200 bhp,0.446040,First Owner,0.150465,23.00
4,10k-30k km,0.019654,0.583102,Automatic,Hatchback,0.364112,Baleno 1.2 CVT Zeta,2.747703,Maruti,0.073531,...,0.180334,61113.0,50.000 km a 150.000 km,0.255059,83.1,0-100 bhp,0.206644,First Owner,0.150465,6.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13420,10k-30k km,0.019654,0.583102,Automatic,MUV,1.347597,Carnival Premium,3.650793,Kia,0.903640,...,0.514919,80000.0,50.000 km a 150.000 km,0.255059,197.2,100-200 bhp,0.446040,Second Owner,0.620328,26.50
13421,10k-30k km,0.019654,0.131359,Manual,Hatchback,0.364112,i20 1.2 Magna Executive,2.951823,Hyundai,0.073531,...,0.180334,17923.0,Até 50.000 km,0.364786,81.8,0-100 bhp,0.206644,First Owner,0.150465,5.87
13422,10k-30k km,0.019654,0.131359,Manual,Sedan,0.578053,Rapid 1.5 TDI Ambition BSIV,3.282816,Skoda,0.903640,...,0.514919,63389.0,50.000 km a 150.000 km,0.255059,108.6,100-200 bhp,0.446040,Second Owner,0.620328,7.43
13423,10k-30k km,0.019654,0.131359,Manual,SUV,0.598869,Vitara Brezza ZDi,2.747703,Maruti,0.073531,...,0.514919,40000.0,Até 50.000 km,0.364786,88.5,0-100 bhp,0.206644,Second Owner,0.620328,9.45
13424,10k-30k km,0.019654,0.131359,Manual,Sedan,0.578053,Amaze S i-Vtech,2.428944,Honda,0.073531,...,0.180334,33046.0,Até 50.000 km,0.364786,86.7,0-100 bhp,0.206644,First Owner,0.150465,4.55

In [43]:
import pandas as pd



# Ver as colunas de cada DataFrame
print("Colunas do DataFrame 'df':")
print(df.columns)

print("\nColunas do DataFrame 'dft':")
print(dft.columns)

Colunas do DataFrame 'df':
Index(['full_name', 'registered_year', 'engine_capacity', 'insurance',
       'transmission_type', 'kms_driven', 'owner_type', 'fuel_type',
       'max_power', 'seats', 'mileage', 'body_type', 'city', 'ID'],
      dtype='object')

Colunas do DataFrame 'dft':
Index(['mileage_group', 'id_mileage_group', 'id_transmissao',
       'transmission_type', 'body_type', 'id_body_type', 'modelo',
       'id_modelos', 'marca', 'id_categoria_marca', 'ano', 'city', 'id_city',
       'insurance', 'id_insurance', 'seats', 'engine_capacity',
       'engine_capacity_group', 'id_engine_capacity_group', 'fuel_type',
       'id_fuel_type', 'kms_driven', 'kms_group', 'id_kms_group', 'max_power',
       'max_power_group', 'id_max_power_group', 'owner_type', 'id_owner_type',
       'resale_price_Lakh'],
      dtype='object')

In [44]:
# KMS __________________________________________________
#remove kms from kms_driven
df['kms_driven'] = df['kms_driven'].str.replace('Kms', '')
# Remove , and blanks from 'kms_driven'
df['kms_driven'] = df['kms_driven'].str.replace(',', '').str.strip()
df = df.astype({
   
    'kms_driven': float,
   
})

In [45]:
#MILEAGE
#assign value to blank lines
df['mileage'] = df['mileage'].fillna(0)

df = df[df['mileage'].notna()]
consumo_correto = []

for i in df['mileage']:
    match = re.search(r'(\d+.\d+|\d+)', str(i))  # Encontrar números (com ou sem ponto decimal)

    if match:
        valor = float(match.group())

        if 'km/kg' in str(i):
            valor *= 1.40  # Converter de km/kg para kmpl

        consumo_correto.append(valor)

df['mileage'] = consumo_correto

In [46]:
# groups kms

limites = [0, 50000, 150000, 300000, 600000, 900000, float('inf')]  
rotulos = ['Até 50.000 km', '50.000 km a 150.000 km', '150.000 km a 300.000 km', '300.000 km a 600.000 km', '600.000 km a 900.000 km', 'Acima de 900.000 km']

df['kms_group'] = pd.cut(df['kms_driven'], bins=limites, labels=rotulos, right=False)

df.loc[df['kms_driven'] == 1200000, 'kms_group'] = 'Acima de 900.000 km'

In [47]:
# Criar um dicionário de mapeamento de 'max_power_group' para 'id_max_power_group' em dft
mapeamento_max_power_group = dict(zip(dft['kms_group'], dft['id_kms_group']))

# Criar uma nova coluna 'id_max_power_group' em df com base na correspondência de 'max_power_group' em dft
df['id_kms_group'] = df['kms_group'].map(mapeamento_max_power_group)

In [48]:
# SEATS __________________________________________________
# Check for model cars with missing values in the 'seats' column
distinct_full_names_with_blank_seats = df[df['seats'].isnull()]['full_name'].unique()
print('Distinct full names with blank seats:')
for full_name in distinct_full_names_with_blank_seats:
    print(full_name)

# Update number of seats based on conditions
df.loc[df['full_name'].isin(['2009 Maruti Estilo LXI', '2019 Nissan Kicks Diesel', '2010 Maruti Estilo LXI']), 'seats'] = 5
df.loc[df['full_name'] == '2008 Ford Endeavour 3.0 4x4 Thunder Plus', 'seats'] = 7

Distinct full names with blank seats:
2005 Honda City 1.5 EXI
2009 Maruti Estilo LXI
2012 Honda Jazz Select Edition

In [49]:
# Substituir os valores nulos na coluna 'seats' por 5
df['seats'].fillna(5, inplace=True)

In [50]:
# Substituir os valores 'Third Party insurance' por 'Third Party' em df
df['insurance'] = df['insurance'].replace('Third Party insurance', 'Third Party', regex=True)

# Substituir os valores NaN por 'No Insurance' em df
df['insurance'].fillna('No Insurance', inplace=True)

# Visualizar a coluna 'insurance' atualizada em df
print(df['insurance'].unique())
print(dft['id_insurance'].unique())

['Comprehensive' 'Not Available' 'Third Party' 'Zero Dep' 'No Insurance']
[0.25663332 1.30640077 0.44540821 1.41864433 3.34976304]

In [51]:

print(df['insurance'].unique())
print(dft['insurance'].unique())

['Comprehensive' 'Not Available' 'Third Party' 'Zero Dep' 'No Insurance']
['Third Party' 'Zero Dep' 'Comprehensive' 'Not Available' 'No Insurance']

In [52]:
# Mapear os valores desejados em 'df' para os valores correspondentes em 'dft'
mapeamento_valores = {
    'Third Party insurance': 'Third Party',
    pd.NA: 'No Insurance'
}

# Aplicar as transformações nos valores da coluna 'insurance' em 'df'
df['insurance'] = df['insurance'].replace(mapeamento_valores).fillna('No Insurance')

# Visualizar os valores únicos após as transformações em 'df'
print(df['insurance'].unique())

['Comprehensive' 'Not Available' 'Third Party' 'Zero Dep' 'No Insurance']

In [53]:
# ENGINE __________________________________________________
#remove cc from engine_capacity
df['engine_capacity'] = df['engine_capacity'].str.replace('cc', '')

df = df.astype({
    
    'engine_capacity': float,
  
})

# groups engine_capacity

limites = [0,1, 1000, 2000, 3000, 4000, float('inf')]  
rotulos = ['Elétrico', 'até 1000 cc', 'até 2000 cc', 'até 3000 cc', 'até 4000 cc', 'mais de 4000 cc']

df['engine_capacity_group'] = pd.cut(df['engine_capacity'], bins=limites, labels=rotulos, right=False)

In [54]:
# Criar um dicionário de mapeamento de 'max_power_group' para 'id_max_power_group' em dft
mapeamento_max_power_group = dict(zip(dft['engine_capacity_group'], dft['id_engine_capacity_group']))

# Criar uma nova coluna 'id_max_power_group' em df com base na correspondência de 'max_power_group' em dft
df['id_engine_capacity_group'] = df['engine_capacity_group'].map(mapeamento_max_power_group)

In [55]:
# MAX POWER 
# #convert to bhp__________________________________________________
Correct_Max_Power = []
for power in df['max_power']:
    if pd.notna(power):
        if isinstance(power, str):
            if 'bhp' in power:
                num_bhp = float(re.search(r'\d+.?\d', power).group())
                Correct_Max_Power.append(num_bhp)
            elif 'PS' in power:
                num_ps = float(re.search(r'\d+.?\d', power).group())
                num_bhp = round(num_ps * 0.98632, 2)
                Correct_Max_Power.append(num_bhp)
            else:
                num = re.search(r'\d+\.?\d*', power)
                Correct_Max_Power.append(float(num.group()) if num else None)
        else:
            Correct_Max_Power.append(power)
    else:
        Correct_Max_Power.append(None)


# Convert not NaN to float
Correct_Max_Power = [float(value) if value is not None else value for value in Correct_Max_Power]

df['max_power'] = Correct_Max_Power

#Create grupos

# groups max_power


limites = [0, 100, 200, 300, 400, 500, 600]  
rotulos = ['0-100 bhp', '100-200 bhp', '200-300 bhp', '300-400 bhp', '400-500 bhp', '500-600 bhp']

df['max_power_group'] = pd.cut(df['max_power'], bins=limites, labels=rotulos, right=False)

#Create grupos

# groups mileaage
# Define os limites para os grupos de forma crescente
limites_mileage = [0, 10.000, 30.000, 50.000, 70.000, 90.000, float('inf')]  # Usando float('inf') para incluir todos os valores restantes

# Define os rótulos para os grupos
rotulos_mileage = ['0-10k km', '10k-30k km', '30k-50k km', '50k-70k km', '70k-90k km', '90k+ km']

# Cria a nova coluna 'mileage_group' com base nos limites e rótulos definidos
df['mileage_group'] = pd.cut(df['mileage'], bins=limites_mileage, labels=rotulos_mileage, right=False)

In [56]:
dft

,mileage_group,id_mileage_group,id_transmissao,transmission_type,body_type,id_body_type,modelo,id_modelos,marca,id_categoria_marca,...,id_fuel_type,kms_driven,kms_group,id_kms_group,max_power,max_power_group,id_max_power_group,owner_type,id_owner_type,resale_price_Lakh
0,10k-30k km,0.019654,0.131359,Manual,Hatchback,0.364112,Tiago XZ Plus,3.086522,Tata,0.073531,...,0.180334,30910.0,Até 50.000 km,0.364786,83.8,0-100 bhp,0.206644,First Owner,0.150465,5.66
1,10k-30k km,0.019654,0.131359,Manual,SUV,0.598869,WR-V i-VTEC VX,2.403638,Honda,0.073531,...,0.180334,48089.0,Até 50.000 km,0.364786,88.7,0-100 bhp,0.206644,Third Owner,1.365236,6.64
2,10k-30k km,0.019654,0.131359,Manual,Sedan,0.578053,City i VTEC SV,2.583846,Honda,0.073531,...,0.180334,51000.0,50.000 km a 150.000 km,0.255059,117.3,100-200 bhp,0.446040,Second Owner,0.620328,5.65
3,10k-30k km,0.019654,0.583102,Automatic,SUV,0.598869,New Safari XZA Plus Adventure Edition AT BSVI,3.650793,Tata,0.073531,...,0.514919,30000.0,Até 50.000 km,0.364786,167.6,100-200 bhp,0.446040,First Owner,0.150465,23.00
4,10k-30k km,0.019654,0.583102,Automatic,Hatchback,0.364112,Baleno 1.2 CVT Zeta,2.747703,Maruti,0.073531,...,0.180334,61113.0,50.000 km a 150.000 km,0.255059,83.1,0-100 bhp,0.206644,First Owner,0.150465,6.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13420,10k-30k km,0.019654,0.583102,Automatic,MUV,1.347597,Carnival Premium,3.650793,Kia,0.903640,...,0.514919,80000.0,50.000 km a 150.000 km,0.255059,197.2,100-200 bhp,0.446040,Second Owner,0.620328,26.50
13421,10k-30k km,0.019654,0.131359,Manual,Hatchback,0.364112,i20 1.2 Magna Executive,2.951823,Hyundai,0.073531,...,0.180334,17923.0,Até 50.000 km,0.364786,81.8,0-100 bhp,0.206644,First Owner,0.150465,5.87
13422,10k-30k km,0.019654,0.131359,Manual,Sedan,0.578053,Rapid 1.5 TDI Ambition BSIV,3.282816,Skoda,0.903640,...,0.514919,63389.0,50.000 km a 150.000 km,0.255059,108.6,100-200 bhp,0.446040,Second Owner,0.620328,7.43
13423,10k-30k km,0.019654,0.131359,Manual,SUV,0.598869,Vitara Brezza ZDi,2.747703,Maruti,0.073531,...,0.514919,40000.0,Até 50.000 km,0.364786,88.5,0-100 bhp,0.206644,Second Owner,0.620328,9.45
13424,10k-30k km,0.019654,0.131359,Manual,Sedan,0.578053,Amaze S i-Vtech,2.428944,Honda,0.073531,...,0.180334,33046.0,Até 50.000 km,0.364786,86.7,0-100 bhp,0.206644,First Owner,0.150465,4.55

In [57]:
print("\nColunas do DataFrame 'dft':")
print(dft.columns)

Colunas do DataFrame 'dft':
Index(['mileage_group', 'id_mileage_group', 'id_transmissao',
       'transmission_type', 'body_type', 'id_body_type', 'modelo',
       'id_modelos', 'marca', 'id_categoria_marca', 'ano', 'city', 'id_city',
       'insurance', 'id_insurance', 'seats', 'engine_capacity',
       'engine_capacity_group', 'id_engine_capacity_group', 'fuel_type',
       'id_fuel_type', 'kms_driven', 'kms_group', 'id_kms_group', 'max_power',
       'max_power_group', 'id_max_power_group', 'owner_type', 'id_owner_type',
       'resale_price_Lakh'],
      dtype='object')

In [58]:
# Criar um dicionário de mapeamento de 'max_power_group' para 'id_max_power_group' em dft
mapeamento_mileage_group = dict(zip(dft['mileage_group'], dft['id_mileage_group']))

# Criar uma nova coluna 'id_max_power_group' em df com base na correspondência de 'max_power_group' em dft
df['id_mileage_group'] = df['mileage_group'].map(mapeamento_mileage_group)

In [59]:
# Criar um dicionário de mapeamento de 'max_power_group' para 'id_max_power_group' em dft
mapeamento_max_power_group = dict(zip(dft['max_power_group'], dft['id_max_power_group']))

# Criar uma nova coluna 'id_max_power_group' em df com base na correspondência de 'max_power_group' em dft
df['id_max_power_group'] = df['max_power_group'].map(mapeamento_max_power_group)

In [60]:
df

,full_name,registered_year,engine_capacity,insurance,transmission_type,kms_driven,owner_type,fuel_type,max_power,seats,...,city,ID,kms_group,id_kms_group,engine_capacity_group,id_engine_capacity_group,max_power_group,mileage_group,id_mileage_group,id_max_power_group
0,2017 Hyundai Grand i10 1.2 Kappa Sportz Option,Jun 2017,1197.0,Comprehensive,Manual,53658.0,First Owner,Petrol,81.8,5.0,...,Mumbai,0,50.000 km a 150.000 km,0.255059,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644
1,2020 Maruti Swift AMT VXI,Feb 2021,1197.0,Not Available,Automatic,33055.0,Second Owner,Petrol,81.8,5.0,...,Jaipur,1,Até 50.000 km,0.364786,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644
2,2010 Maruti Zen Estilo LX BSIII,Jul 2010,998.0,Third Party,Manual,90385.0,Third Owner,Petrol,67.1,5.0,...,Chandigarh,2,50.000 km a 150.000 km,0.255059,até 1000 cc,0.776698,0-100 bhp,10k-30k km,0.019654,0.206644
3,2010 Maruti Alto LXi,2010,796.0,Third Party,Manual,110000.0,First Owner,Petrol,46.3,5.0,...,Delhi,3,50.000 km a 150.000 km,0.255059,até 1000 cc,0.776698,0-100 bhp,10k-30k km,0.019654,0.206644
4,2018 Hyundai i20 Active S Petrol,Oct 2018,1197.0,Comprehensive,Manual,58000.0,Second Owner,Petrol,81.8,5.0,...,Delhi,4,50.000 km a 150.000 km,0.255059,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,2022 Tata Tigor EV XZ Plus,2022,NaN,Third Party,Automatic,30000.0,First Owner,Electric,73.7,5.0,...,Pune,3485,Até 50.000 km,0.364786,NaN,4.127914,0-100 bhp,0-10k km,1.562066,0.206644
3486,2017 Renault KWID 1.0 RXT,Apr 2017,999.0,Third Party,Manual,64024.0,First Owner,Petrol,67.0,5.0,...,Bangalore,3486,50.000 km a 150.000 km,0.255059,até 1000 cc,0.776698,0-100 bhp,10k-30k km,0.019654,0.206644
3487,2017 Honda City i VTEC VX,Dec 2017,1497.0,Comprehensive,Manual,39000.0,First Owner,Petrol,117.3,5.0,...,Delhi,3487,Até 50.000 km,0.364786,até 2000 cc,0.126137,100-200 bhp,10k-30k km,0.019654,0.446040
3488,2016 Honda Jazz 1.2 V i VTEC,Jun 2016,1199.0,Comprehensive,Manual,33000.0,First Owner,Petrol,88.7,5.0,...,Mumbai,3488,Até 50.000 km,0.364786,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644
3489,2017 Maruti Swift VXI,Mar 2017,1197.0,Comprehensive,Manual,14097.0,Second Owner,Petrol,88.5,5.0,...,Delhi,3489,Até 50.000 km,0.364786,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644

In [61]:
df['max_power_group'] = df['max_power_group'].astype('string')
df['engine_capacity_group'] = df['engine_capacity_group'].astype('string')
print(df.dtypes)

full_name                           object
registered_year                     object
engine_capacity                    float64
insurance                           object
transmission_type                   object
kms_driven                         float64
owner_type                          object
fuel_type                           object
max_power                          float64
seats                              float64
mileage                            float64
body_type                           object
city                                object
ID                                   int64
kms_group                         category
id_kms_group                       float64
engine_capacity_group       string[python]
id_engine_capacity_group           float64
max_power_group             string[python]
mileage_group                     category
id_mileage_group                   float64
id_max_power_group                 float64
dtype: object

In [62]:
#BODY TYPE ----------------------
#Replace the missing types and the ones that were wrong
df.loc[df['full_name'].isin(['2009 Maruti Estilo LXI', '2019 Nissan Kicks Diesel', '2010 Maruti Estilo LXI', '2019 Maruti Wagon R ZXI AMT 1.2BSIV',
                             '2016 Mercedes-Benz B Class B180 Sport', '2016 Mercedes-Benz A Class A200 D Sport Edition',
                             '2004 Tata Indigo Marina GLX', '2017 Volvo V40 D3 R Design']), 'body_type'] = 'Hatchback'
df.loc[df['full_name'].isin(['2005 Tata Sumo Victa EX 10/7 Str BSII', '2008 Tata Sumo CX', '2010 Tata New Safari DICOR 2.2 EX 4x2', 
                             '2017 Mahindra KUV 100 mFALCON G80 K8', '2019 Mahindra Bolero Camper GOLD ZX 2WD']), 'body_type'] = 'SUV'
df.loc[df['full_name'].isin(['2015 Honda Mobilio E i-DTEC', '2018 Maruti Eeco 5 Seater AC BSIV', '2016 Datsun GO Plus A']), 'body_type'] = 'MUV'
df.loc[df['full_name'].isin(['2021 BMW 7 Series 730Ld DPE Signature','2006 Hyundai Accent CRDi', '2007 Maruti SX4 Vxi BSIII',
                             '2020 Mercedes-Benz S-Class Maybach S560', '2004 Skoda Octavia 1.8 Turbo Petrol RS MT']), 'body_type'] = 'Sedan'
df.loc[df['full_name'].isin(['2012 Mercedes-Benz SLK-Class SLK 350', '2013 Mercedes-Benz E-Class E350 Cabriolet', 
                             '2009 Mercedes-Benz SLK-Class 55 AMG']), 'body_type'] = 'Convertibles'
df.loc[df['full_name'] == '2011 Jaguar XK R V8 Coupe', 'body_type'] = 'Coupe'
df.loc[df['full_name'].isin(['2015 Chevrolet Enjoy 1.4 LS 7', '2004 Maruti Versa DX2 8-SEATER BSIII TWIN A/C', '2021 Maruti Eeco 5 STR With AC Plus HTR CNG',
                             '2022 Maruti Eeco 5 Seater AC 2020-2022', '2022 Maruti Eeco 5 Seater AC BSVI', '2017 Maruti Eeco Flexi Green', 
                             '2013 Maruti Omni Limited Edition', '2021 Maruti Eeco CNG 5 Seater AC', '2019 Maruti Eeco CNG 5 Seater AC BSIV', 
                             '2019 Maruti Eeco 5 Seater AC', '2013 Maruti Eeco 5 Seater Standard BSIV', '2015 Maruti Omni CNG', 
                             '2015 Maruti Omni MPI CARGO BSIV', '2016 Maruti Eeco CNG 5 Seater AC BSIV', '2013 Toyota Innova 2.5 E Diesel MS 7-seater',
                             '2015 Chevrolet Enjoy 1.4 LS 7']), 'body_type'] = 'Minivans'
df.loc[df['full_name'].isin(['2014 Tata Xenon XT EX 4X2', '2019 Isuzu D-Max High']), 'body_type'] = 'Pickup'

# Check
distinct_full_names_with_blank_body_type = df[df['body_type'].isnull()]['full_name'].unique()
print('Distinct full names with blank body_type:')
for full_name in distinct_full_names_with_blank_body_type:
    print(full_name)

Distinct full names with blank body_type:

In [63]:
# Contar a quantidade de NaN em cada coluna do DataFrame X
nan_count = df.isna().sum()

# Exibir a contagem de NaN por coluna
print(nan_count)

full_name                    0
registered_year             15
engine_capacity              5
insurance                    0
transmission_type            0
kms_driven                   0
owner_type                   9
fuel_type                    0
max_power                   13
seats                        0
mileage                      0
body_type                    0
city                         0
ID                           0
kms_group                    0
id_kms_group                 0
engine_capacity_group        5
id_engine_capacity_group     0
max_power_group             13
mileage_group                0
id_mileage_group             0
id_max_power_group          13
dtype: int64

In [64]:
import pandas as pd

def substituir_valores(df, coluna_alvo, mapeamento):
    df[coluna_alvo] = df[coluna_alvo].replace(mapeamento).fillna(df[coluna_alvo])



# Criar os mapeamentos desejados para cada coluna
mapeamento_id_cidade = dict(zip(dft['city'], dft['id_city']))
mapeamento_id_body_type = dict(zip(dft['body_type'], dft['id_body_type']))
mapeamento_id_owner_type = dict(zip(dft['owner_type'], dft['id_owner_type']))
mapeamento_id_fuel_type = dict(zip(dft['fuel_type'], dft['id_fuel_type']))
mapeamento_id_insurance = dict(zip(dft['insurance'], dft['id_insurance']))



# Chamar a função para substituir os valores nas respectivas colunas
substituir_valores(df, 'city', mapeamento_id_cidade)
substituir_valores(df, 'body_type', mapeamento_id_body_type)
substituir_valores(df, 'owner_type', mapeamento_id_owner_type)
substituir_valores(df, 'fuel_type', mapeamento_id_fuel_type)
substituir_valores(df, 'insurance', mapeamento_id_insurance)


# Visualizar o DataFrame 'df' atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...      city    ID  \
0      0.180334       81.8    5.0  ...  0.922710     0
1      0.180334       81.8    5.0  ...  1.281577     1
2      0.180334       67.1    5.0  ...  1.593888     2
3      0.180334       46.3    5.0  ...  0.767700     3
4      0.180334       81.8    5.0  ...  0.767700     4
...         ...        ...    ...  ...       ...   ...
3485   2.455816       73.7    5.0  ...  1.096102  3485
3486   0.180334       67.0    5.0  ...  0.868320  3486
3487   0.180334      117.3    5.0  ...  0.767700  3487
3488   0.180334       88.7    5.0  ...  0.922710  3488
3489   0.180334       88.5    5.0  ...  0.767700  3489

                   kms_group  id_kms_group engine_capacity_group  \
0     50.000 km a 150.000 km      0.255059           até 2000 cc
1              Até 50.000 km      0.364786           até 2000 cc
2     50.000 km a 150.000 km      0.255059           até 1000 cc
3     50.000 km a 150.000 km      0.255059           até 1000 cc
4     50.000 km a 150.000 km      0.255059           até 2000 cc
...                      ...           ...                   ...
3485           Até 50.000 km      0.364786                  <NA>
3486  50.000 km a 150.000 km      0.255059           até 1000 cc
3487           Até 50.000 km      0.364786           até 2000 cc
3488           Até 50.000 km      0.364786           até 2000 cc
3489           Até 50.000 km      0.364786           até 2000 cc

      id_engine_capacity_group max_power_group  mileage_group  \
0                     0.126137       0-100 bhp     10k-30k km
1                     0.126137       0-100 bhp     10k-30k km
2                     0.776698       0-100 bhp     10k-30k km
3                     0.776698       0-100 bhp     10k-30k km
4                     0.126137       0-100 bhp     10k-30k km
...                        ...             ...            ...
3485                  4.127914       0-100 bhp       0-10k km
3486                  0.776698       0-100 bhp     10k-30k km
3487                  0.126137     100-200 bhp     10k-30k km
3488                  0.126137       0-100 bhp     10k-30k km
3489                  0.126137       0-100 bhp     10k-30k km

     id_mileage_group id_max_power_group
0            0.019654           0.206644
1            0.019654           0.206644
2            0.019654           0.206644
3            0.019654           0.206644
4            0.019654           0.206644
...               ...                ...
3485         1.562066           0.206644
3486         0.019654           0.206644
3487         0.019654           0.446040
3488         0.019654           0.206644
3489         0.019654           0.206644

[3490 rows x 22 columns]

In [65]:
import pandas as pd
import re

# Supondo que já carregou os DataFrames df e dft

# Função para extrair a marca a partir da coluna 'full_name' em df
def extrair_marca(nome):
    match = re.search(r'\d{4}\s(.+?)\s', nome)  # Expressão regular para pegar a marca após o ano
    if match:
        return match.group(1)
    else:
        return None

# Aplicar a função para extrair a marca e criar uma nova coluna 'marca' em df
df['marca'] = df['full_name'].apply(extrair_marca)

# Mapear as marcas de df para a coluna 'marca' em dft
mapeamento_marca = dict(zip(dft['marca'], dft['id_categoria_marca']))

# Criar uma nova coluna 'id_categoria_marca' em df com base na correspondência de marcas em dft
df['id_categoria_marca'] = df['marca'].map(mapeamento_marca)

# Visualizar o DataFrame df atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...               kms_group id_kms_group  \
0      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
1      0.180334       81.8    5.0  ...           Até 50.000 km     0.364786
2      0.180334       67.1    5.0  ...  50.000 km a 150.000 km     0.255059
3      0.180334       46.3    5.0  ...  50.000 km a 150.000 km     0.255059
4      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
...         ...        ...    ...  ...                     ...          ...
3485   2.455816       73.7    5.0  ...           Até 50.000 km     0.364786
3486   0.180334       67.0    5.0  ...  50.000 km a 150.000 km     0.255059
3487   0.180334      117.3    5.0  ...           Até 50.000 km     0.364786
3488   0.180334       88.7    5.0  ...           Até 50.000 km     0.364786
3489   0.180334       88.5    5.0  ...           Até 50.000 km     0.364786

      engine_capacity_group  id_engine_capacity_group max_power_group  \
0               até 2000 cc                  0.126137       0-100 bhp
1               até 2000 cc                  0.126137       0-100 bhp
2               até 1000 cc                  0.776698       0-100 bhp
3               até 1000 cc                  0.776698       0-100 bhp
4               até 2000 cc                  0.126137       0-100 bhp
...                     ...                       ...             ...
3485                   <NA>                  4.127914       0-100 bhp
3486            até 1000 cc                  0.776698       0-100 bhp
3487            até 2000 cc                  0.126137     100-200 bhp
3488            até 2000 cc                  0.126137       0-100 bhp
3489            até 2000 cc                  0.126137       0-100 bhp

      mileage_group id_mileage_group  id_max_power_group    marca  \
0        10k-30k km         0.019654            0.206644  Hyundai
1        10k-30k km         0.019654            0.206644   Maruti
2        10k-30k km         0.019654            0.206644   Maruti
3        10k-30k km         0.019654            0.206644   Maruti
4        10k-30k km         0.019654            0.206644  Hyundai
...             ...              ...                 ...      ...
3485       0-10k km         1.562066            0.206644     Tata
3486     10k-30k km         0.019654            0.206644  Renault
3487     10k-30k km         0.019654            0.446040    Honda
3488     10k-30k km         0.019654            0.206644    Honda
3489     10k-30k km         0.019654            0.206644   Maruti

     id_categoria_marca
0              0.073531
1              0.073531
2              0.073531
3              0.073531
4              0.073531
...                 ...
3485           0.073531
3486           0.073531
3487           0.073531
3488           0.073531
3489           0.073531

[3490 rows x 24 columns]

In [66]:
import pandas as pd

def adicionar_0_1_maior_valor(df, dft):
    # Encontrar o maior valor na coluna 'id_categoria_marca' em dft
    maior_valor_categoria_marca_dft = dft['id_categoria_marca'].max()

    # Adicionar 0.1 ao maior valor encontrado
    novo_valor = maior_valor_categoria_marca_dft + 0.1

    # Substituir os valores NaN na coluna 'id_categoria_marca' em df pelo novo valor
    df['id_categoria_marca'].fillna(novo_valor, inplace=True)

# Utilização da função com os DataFrames 'df' e 'dft'
adicionar_0_1_maior_valor(df, dft)

# Visualizar o DataFrame 'df' atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...               kms_group id_kms_group  \
0      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
1      0.180334       81.8    5.0  ...           Até 50.000 km     0.364786
2      0.180334       67.1    5.0  ...  50.000 km a 150.000 km     0.255059
3      0.180334       46.3    5.0  ...  50.000 km a 150.000 km     0.255059
4      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
...         ...        ...    ...  ...                     ...          ...
3485   2.455816       73.7    5.0  ...           Até 50.000 km     0.364786
3486   0.180334       67.0    5.0  ...  50.000 km a 150.000 km     0.255059
3487   0.180334      117.3    5.0  ...           Até 50.000 km     0.364786
3488   0.180334       88.7    5.0  ...           Até 50.000 km     0.364786
3489   0.180334       88.5    5.0  ...           Até 50.000 km     0.364786

      engine_capacity_group  id_engine_capacity_group max_power_group  \
0               até 2000 cc                  0.126137       0-100 bhp
1               até 2000 cc                  0.126137       0-100 bhp
2               até 1000 cc                  0.776698       0-100 bhp
3               até 1000 cc                  0.776698       0-100 bhp
4               até 2000 cc                  0.126137       0-100 bhp
...                     ...                       ...             ...
3485                   <NA>                  4.127914       0-100 bhp
3486            até 1000 cc                  0.776698       0-100 bhp
3487            até 2000 cc                  0.126137     100-200 bhp
3488            até 2000 cc                  0.126137       0-100 bhp
3489            até 2000 cc                  0.126137       0-100 bhp

      mileage_group id_mileage_group  id_max_power_group    marca  \
0        10k-30k km         0.019654            0.206644  Hyundai
1        10k-30k km         0.019654            0.206644   Maruti
2        10k-30k km         0.019654            0.206644   Maruti
3        10k-30k km         0.019654            0.206644   Maruti
4        10k-30k km         0.019654            0.206644  Hyundai
...             ...              ...                 ...      ...
3485       0-10k km         1.562066            0.206644     Tata
3486     10k-30k km         0.019654            0.206644  Renault
3487     10k-30k km         0.019654            0.446040    Honda
3488     10k-30k km         0.019654            0.206644    Honda
3489     10k-30k km         0.019654            0.206644   Maruti

     id_categoria_marca
0              0.073531
1              0.073531
2              0.073531
3              0.073531
4              0.073531
...                 ...
3485           0.073531
3486           0.073531
3487           0.073531
3488           0.073531
3489           0.073531

[3490 rows x 24 columns]

In [67]:
import pandas as pd

def adicionar_0_1_maior_valor(df, dft):
    # Encontrar o maior valor na coluna 'id_categoria_marca' em dft
    maior_valor_id_owner_type_dft = dft['id_owner_type'].max()

    # Adicionar 0.1 ao maior valor encontrado
    novo_valor = maior_valor_id_owner_type_dft + 0.1

    # Substituir os valores NaN na coluna 'id_categoria_marca' em df pelo novo valor
    df['owner_type'].fillna(novo_valor, inplace=True)

# Utilização da função com os DataFrames 'df' e 'dft'
adicionar_0_1_maior_valor(df, dft)

# Visualizar o DataFrame 'df' atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...               kms_group id_kms_group  \
0      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
1      0.180334       81.8    5.0  ...           Até 50.000 km     0.364786
2      0.180334       67.1    5.0  ...  50.000 km a 150.000 km     0.255059
3      0.180334       46.3    5.0  ...  50.000 km a 150.000 km     0.255059
4      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
...         ...        ...    ...  ...                     ...          ...
3485   2.455816       73.7    5.0  ...           Até 50.000 km     0.364786
3486   0.180334       67.0    5.0  ...  50.000 km a 150.000 km     0.255059
3487   0.180334      117.3    5.0  ...           Até 50.000 km     0.364786
3488   0.180334       88.7    5.0  ...           Até 50.000 km     0.364786
3489   0.180334       88.5    5.0  ...           Até 50.000 km     0.364786

      engine_capacity_group  id_engine_capacity_group max_power_group  \
0               até 2000 cc                  0.126137       0-100 bhp
1               até 2000 cc                  0.126137       0-100 bhp
2               até 1000 cc                  0.776698       0-100 bhp
3               até 1000 cc                  0.776698       0-100 bhp
4               até 2000 cc                  0.126137       0-100 bhp
...                     ...                       ...             ...
3485                   <NA>                  4.127914       0-100 bhp
3486            até 1000 cc                  0.776698       0-100 bhp
3487            até 2000 cc                  0.126137     100-200 bhp
3488            até 2000 cc                  0.126137       0-100 bhp
3489            até 2000 cc                  0.126137       0-100 bhp

      mileage_group id_mileage_group  id_max_power_group    marca  \
0        10k-30k km         0.019654            0.206644  Hyundai
1        10k-30k km         0.019654            0.206644   Maruti
2        10k-30k km         0.019654            0.206644   Maruti
3        10k-30k km         0.019654            0.206644   Maruti
4        10k-30k km         0.019654            0.206644  Hyundai
...             ...              ...                 ...      ...
3485       0-10k km         1.562066            0.206644     Tata
3486     10k-30k km         0.019654            0.206644  Renault
3487     10k-30k km         0.019654            0.446040    Honda
3488     10k-30k km         0.019654            0.206644    Honda
3489     10k-30k km         0.019654            0.206644   Maruti

     id_categoria_marca
0              0.073531
1              0.073531
2              0.073531
3              0.073531
4              0.073531
...                 ...
3485           0.073531
3486           0.073531
3487           0.073531
3488           0.073531
3489           0.073531

[3490 rows x 24 columns]

In [68]:
#soluçoes id_ENGINE

import pandas as pd

def adicionar_0_1_maior_valorENG(df, dft):
    # Encontrar o maior valor na coluna 'id_categoria_marca' em dft
    maior_valor_id_engine_dft = dft['id_engine_capacity_group'].max()

    # Adicionar 0.1 ao maior valor encontrado
    novo_valor = maior_valor_id_engine_dft + 0.1

    # Substituir os valores NaN na coluna 'id_categoria_marca' em df pelo novo valor
    df['id_engine_capacity_group'].fillna(novo_valor, inplace=True)

# Utilização da função com os DataFrames 'df' e 'dft'
adicionar_0_1_maior_valorENG(df, dft)

# Visualizar o DataFrame 'df' atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...               kms_group id_kms_group  \
0      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
1      0.180334       81.8    5.0  ...           Até 50.000 km     0.364786
2      0.180334       67.1    5.0  ...  50.000 km a 150.000 km     0.255059
3      0.180334       46.3    5.0  ...  50.000 km a 150.000 km     0.255059
4      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
...         ...        ...    ...  ...                     ...          ...
3485   2.455816       73.7    5.0  ...           Até 50.000 km     0.364786
3486   0.180334       67.0    5.0  ...  50.000 km a 150.000 km     0.255059
3487   0.180334      117.3    5.0  ...           Até 50.000 km     0.364786
3488   0.180334       88.7    5.0  ...           Até 50.000 km     0.364786
3489   0.180334       88.5    5.0  ...           Até 50.000 km     0.364786

      engine_capacity_group  id_engine_capacity_group max_power_group  \
0               até 2000 cc                  0.126137       0-100 bhp
1               até 2000 cc                  0.126137       0-100 bhp
2               até 1000 cc                  0.776698       0-100 bhp
3               até 1000 cc                  0.776698       0-100 bhp
4               até 2000 cc                  0.126137       0-100 bhp
...                     ...                       ...             ...
3485                   <NA>                  4.127914       0-100 bhp
3486            até 1000 cc                  0.776698       0-100 bhp
3487            até 2000 cc                  0.126137     100-200 bhp
3488            até 2000 cc                  0.126137       0-100 bhp
3489            até 2000 cc                  0.126137       0-100 bhp

      mileage_group id_mileage_group  id_max_power_group    marca  \
0        10k-30k km         0.019654            0.206644  Hyundai
1        10k-30k km         0.019654            0.206644   Maruti
2        10k-30k km         0.019654            0.206644   Maruti
3        10k-30k km         0.019654            0.206644   Maruti
4        10k-30k km         0.019654            0.206644  Hyundai
...             ...              ...                 ...      ...
3485       0-10k km         1.562066            0.206644     Tata
3486     10k-30k km         0.019654            0.206644  Renault
3487     10k-30k km         0.019654            0.446040    Honda
3488     10k-30k km         0.019654            0.206644    Honda
3489     10k-30k km         0.019654            0.206644   Maruti

     id_categoria_marca
0              0.073531
1              0.073531
2              0.073531
3              0.073531
4              0.073531
...                 ...
3485           0.073531
3486           0.073531
3487           0.073531
3488           0.073531
3489           0.073531

[3490 rows x 24 columns]

In [69]:
#soluçoes id_maxpower

import pandas as pd

def adicionar_0_1_maior_valormax(df, dft):
    # Encontrar o maior valor na coluna 'id_categoria_marca' em dft
    maior_valor_id_max_power_dft = dft['id_max_power_group'].max()

    # Adicionar 0.1 ao maior valor encontrado
    novo_valor = maior_valor_id_max_power_dft + 0.1

    # Substituir os valores NaN na coluna 'id_categoria_marca' em df pelo novo valor
    df['id_max_power_group'].fillna(novo_valor, inplace=True)

# Utilização da função com os DataFrames 'df' e 'dft'
adicionar_0_1_maior_valormax(df, dft)

# Visualizar o DataFrame 'df' atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...               kms_group id_kms_group  \
0      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
1      0.180334       81.8    5.0  ...           Até 50.000 km     0.364786
2      0.180334       67.1    5.0  ...  50.000 km a 150.000 km     0.255059
3      0.180334       46.3    5.0  ...  50.000 km a 150.000 km     0.255059
4      0.180334       81.8    5.0  ...  50.000 km a 150.000 km     0.255059
...         ...        ...    ...  ...                     ...          ...
3485   2.455816       73.7    5.0  ...           Até 50.000 km     0.364786
3486   0.180334       67.0    5.0  ...  50.000 km a 150.000 km     0.255059
3487   0.180334      117.3    5.0  ...           Até 50.000 km     0.364786
3488   0.180334       88.7    5.0  ...           Até 50.000 km     0.364786
3489   0.180334       88.5    5.0  ...           Até 50.000 km     0.364786

      engine_capacity_group  id_engine_capacity_group max_power_group  \
0               até 2000 cc                  0.126137       0-100 bhp
1               até 2000 cc                  0.126137       0-100 bhp
2               até 1000 cc                  0.776698       0-100 bhp
3               até 1000 cc                  0.776698       0-100 bhp
4               até 2000 cc                  0.126137       0-100 bhp
...                     ...                       ...             ...
3485                   <NA>                  4.127914       0-100 bhp
3486            até 1000 cc                  0.776698       0-100 bhp
3487            até 2000 cc                  0.126137     100-200 bhp
3488            até 2000 cc                  0.126137       0-100 bhp
3489            até 2000 cc                  0.126137       0-100 bhp

      mileage_group id_mileage_group  id_max_power_group    marca  \
0        10k-30k km         0.019654            0.206644  Hyundai
1        10k-30k km         0.019654            0.206644   Maruti
2        10k-30k km         0.019654            0.206644   Maruti
3        10k-30k km         0.019654            0.206644   Maruti
4        10k-30k km         0.019654            0.206644  Hyundai
...             ...              ...                 ...      ...
3485       0-10k km         1.562066            0.206644     Tata
3486     10k-30k km         0.019654            0.206644  Renault
3487     10k-30k km         0.019654            0.446040    Honda
3488     10k-30k km         0.019654            0.206644    Honda
3489     10k-30k km         0.019654            0.206644   Maruti

     id_categoria_marca
0              0.073531
1              0.073531
2              0.073531
3              0.073531
4              0.073531
...                 ...
3485           0.073531
3486           0.073531
3487           0.073531
3488           0.073531
3489           0.073531

[3490 rows x 24 columns]

In [70]:
#soluçoes marca

import pandas as pd
import re

# Supondo que já carregou o DataFrame df

# Função para extrair o ano dos primeiros quatro caracteres de 'full_name' em df
def extrair_ano(nome):
    match = re.match(r'\d{4}', nome)  # Expressão regular para pegar os primeiros quatro dígitos (ano)
    if match:
        return match.group()
    else:
        return None

# Aplicar a função para extrair o ano e criar uma nova coluna 'ano' em df
df['ano'] = df['full_name'].apply(extrair_ano)

# Visualizar o DataFrame df com a nova coluna 'ano'
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...  id_kms_group engine_capacity_group  \
0      0.180334       81.8    5.0  ...      0.255059           até 2000 cc
1      0.180334       81.8    5.0  ...      0.364786           até 2000 cc
2      0.180334       67.1    5.0  ...      0.255059           até 1000 cc
3      0.180334       46.3    5.0  ...      0.255059           até 1000 cc
4      0.180334       81.8    5.0  ...      0.255059           até 2000 cc
...         ...        ...    ...  ...           ...                   ...
3485   2.455816       73.7    5.0  ...      0.364786                  <NA>
3486   0.180334       67.0    5.0  ...      0.255059           até 1000 cc
3487   0.180334      117.3    5.0  ...      0.364786           até 2000 cc
3488   0.180334       88.7    5.0  ...      0.364786           até 2000 cc
3489   0.180334       88.5    5.0  ...      0.364786           até 2000 cc

      id_engine_capacity_group  max_power_group mileage_group  \
0                     0.126137        0-100 bhp    10k-30k km
1                     0.126137        0-100 bhp    10k-30k km
2                     0.776698        0-100 bhp    10k-30k km
3                     0.776698        0-100 bhp    10k-30k km
4                     0.126137        0-100 bhp    10k-30k km
...                        ...              ...           ...
3485                  4.127914        0-100 bhp      0-10k km
3486                  0.776698        0-100 bhp    10k-30k km
3487                  0.126137      100-200 bhp    10k-30k km
3488                  0.126137        0-100 bhp    10k-30k km
3489                  0.126137        0-100 bhp    10k-30k km

      id_mileage_group id_max_power_group    marca id_categoria_marca   ano
0             0.019654           0.206644  Hyundai           0.073531  2017
1             0.019654           0.206644   Maruti           0.073531  2020
2             0.019654           0.206644   Maruti           0.073531  2010
3             0.019654           0.206644   Maruti           0.073531  2010
4             0.019654           0.206644  Hyundai           0.073531  2018
...                ...                ...      ...                ...   ...
3485          1.562066           0.206644     Tata           0.073531  2022
3486          0.019654           0.206644  Renault           0.073531  2017
3487          0.019654           0.446040    Honda           0.073531  2017
3488          0.019654           0.206644    Honda           0.073531  2016
3489          0.019654           0.206644   Maruti           0.073531  2017

[3490 rows x 25 columns]

In [71]:
# Contar os valores nulos (NaN) em cada coluna
contagem_nan = df.isna().sum()

# Exibir a contagem de valores nulos em cada coluna
print(contagem_nan)

full_name                    0
registered_year             15
engine_capacity              5
insurance                    0
transmission_type            0
kms_driven                   0
owner_type                   0
fuel_type                    0
max_power                   13
seats                        0
mileage                      0
body_type                    0
city                         0
ID                           0
kms_group                    0
id_kms_group                 0
engine_capacity_group        5
id_engine_capacity_group     0
max_power_group             13
mileage_group                0
id_mileage_group             0
id_max_power_group           0
marca                        0
id_categoria_marca           0
ano                          0
dtype: int64

In [72]:

#soluçoes id_body_type

import pandas as pd

def adicionar_0_1_maior_valormax(df, dft):
    # Encontrar o maior valor na coluna 'id_body_type' em dft
    maior_valor_id_max_power_dft = dft['id_body_type'].max()

    # Adicionar 0.1 ao maior valor encontrado
    novo_valor = maior_valor_id_max_power_dft + 0.1

    # Valores a substituir e seus respectivos substitutos
    substitute_values = {
        'Tata': novo_valor,
        'Mahindra': novo_valor,
        'Maruti': novo_valor,
        'Audi': novo_valor,
        'Toyota': novo_valor,
        'Honda': novo_valor,
        'BMW': novo_valor,
        'Datsun': novo_valor,
        'Chevrolet': novo_valor,
        'Jaguar': novo_valor,
        'Porsche': novo_valor
    }

    # Substituir os valores na coluna 'body_type' pelos valores do dicionário substitute_values
    df['body_type'].replace(substitute_values, inplace=True)



# Utilização da função com os DataFrames 'df' e 'dft'
adicionar_0_1_maior_valormax(df, dft)

# Visualizar o DataFrame 'df' atualizado
print(df)

                                           full_name registered_year  \
0     2017 Hyundai Grand i10 1.2 Kappa Sportz Option        Jun 2017
1                          2020 Maruti Swift AMT VXI        Feb 2021
2                    2010 Maruti Zen Estilo LX BSIII        Jul 2010
3                               2010 Maruti Alto LXi            2010
4                   2018 Hyundai i20 Active S Petrol        Oct 2018
...                                              ...             ...
3485                      2022 Tata Tigor EV XZ Plus            2022
3486                       2017 Renault KWID 1.0 RXT        Apr 2017
3487                       2017 Honda City i VTEC VX        Dec 2017
3488                    2016 Honda Jazz 1.2 V i VTEC        Jun 2016
3489                           2017 Maruti Swift VXI        Mar 2017

      engine_capacity  insurance transmission_type  kms_driven  owner_type  \
0              1197.0   0.445408            Manual     53658.0    0.150465
1              1197.0   1.418644         Automatic     33055.0    0.620328
2               998.0   0.256633            Manual     90385.0    1.365236
3               796.0   0.256633            Manual    110000.0    0.150465
4              1197.0   0.445408            Manual     58000.0    0.620328
...               ...        ...               ...         ...         ...
3485              NaN   0.256633         Automatic     30000.0    0.150465
3486            999.0   0.256633            Manual     64024.0    0.150465
3487           1497.0   0.445408            Manual     39000.0    0.150465
3488           1199.0   0.445408            Manual     33000.0    0.150465
3489           1197.0   0.445408            Manual     14097.0    0.620328

      fuel_type  max_power  seats  ...  id_kms_group  engine_capacity_group  \
0      0.180334       81.8    5.0  ...      0.255059            até 2000 cc
1      0.180334       81.8    5.0  ...      0.364786            até 2000 cc
2      0.180334       67.1    5.0  ...      0.255059            até 1000 cc
3      0.180334       46.3    5.0  ...      0.255059            até 1000 cc
4      0.180334       81.8    5.0  ...      0.255059            até 2000 cc
...         ...        ...    ...  ...           ...                    ...
3485   2.455816       73.7    5.0  ...      0.364786                   <NA>
3486   0.180334       67.0    5.0  ...      0.255059            até 1000 cc
3487   0.180334      117.3    5.0  ...      0.364786            até 2000 cc
3488   0.180334       88.7    5.0  ...      0.364786            até 2000 cc
3489   0.180334       88.5    5.0  ...      0.364786            até 2000 cc

      id_engine_capacity_group  max_power_group mileage_group  \
0                     0.126137        0-100 bhp    10k-30k km
1                     0.126137        0-100 bhp    10k-30k km
2                     0.776698        0-100 bhp    10k-30k km
3                     0.776698        0-100 bhp    10k-30k km
4                     0.126137        0-100 bhp    10k-30k km
...                        ...              ...           ...
3485                  4.127914        0-100 bhp      0-10k km
3486                  0.776698        0-100 bhp    10k-30k km
3487                  0.126137      100-200 bhp    10k-30k km
3488                  0.126137        0-100 bhp    10k-30k km
3489                  0.126137        0-100 bhp    10k-30k km

      id_mileage_group id_max_power_group    marca id_categoria_marca   ano
0             0.019654           0.206644  Hyundai           0.073531  2017
1             0.019654           0.206644   Maruti           0.073531  2020
2             0.019654           0.206644   Maruti           0.073531  2010
3             0.019654           0.206644   Maruti           0.073531  2010
4             0.019654           0.206644  Hyundai           0.073531  2018
...                ...                ...      ...                ...   ...
3485          1.562066           0.206644     Tata           0.073531  2022
3486          0.019654           0.206644  Renault           0.073531  2017
3487          0.019654           0.446040    Honda           0.073531  2017
3488          0.019654           0.206644    Honda           0.073531  2016
3489          0.019654           0.206644   Maruti           0.073531  2017

[3490 rows x 25 columns]

In [73]:
# Obtendo os valores únicos da coluna 'body_type'
valores_unicos_body_type = df['body_type'].unique()

# Exibindo os valores únicos
print(valores_unicos_body_type)

[0.36411207 0.59886912 3.75079304 0.57805311 1.34759698 2.2890652
 3.28281625 3.04873305 3.42894429]

In [74]:
df

,full_name,registered_year,engine_capacity,insurance,transmission_type,kms_driven,owner_type,fuel_type,max_power,seats,...,id_kms_group,engine_capacity_group,id_engine_capacity_group,max_power_group,mileage_group,id_mileage_group,id_max_power_group,marca,id_categoria_marca,ano
0,2017 Hyundai Grand i10 1.2 Kappa Sportz Option,Jun 2017,1197.0,0.445408,Manual,53658.0,0.150465,0.180334,81.8,5.0,...,0.255059,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644,Hyundai,0.073531,2017
1,2020 Maruti Swift AMT VXI,Feb 2021,1197.0,1.418644,Automatic,33055.0,0.620328,0.180334,81.8,5.0,...,0.364786,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644,Maruti,0.073531,2020
2,2010 Maruti Zen Estilo LX BSIII,Jul 2010,998.0,0.256633,Manual,90385.0,1.365236,0.180334,67.1,5.0,...,0.255059,até 1000 cc,0.776698,0-100 bhp,10k-30k km,0.019654,0.206644,Maruti,0.073531,2010
3,2010 Maruti Alto LXi,2010,796.0,0.256633,Manual,110000.0,0.150465,0.180334,46.3,5.0,...,0.255059,até 1000 cc,0.776698,0-100 bhp,10k-30k km,0.019654,0.206644,Maruti,0.073531,2010
4,2018 Hyundai i20 Active S Petrol,Oct 2018,1197.0,0.445408,Manual,58000.0,0.620328,0.180334,81.8,5.0,...,0.255059,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644,Hyundai,0.073531,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3485,2022 Tata Tigor EV XZ Plus,2022,NaN,0.256633,Automatic,30000.0,0.150465,2.455816,73.7,5.0,...,0.364786,<NA>,4.127914,0-100 bhp,0-10k km,1.562066,0.206644,Tata,0.073531,2022
3486,2017 Renault KWID 1.0 RXT,Apr 2017,999.0,0.256633,Manual,64024.0,0.150465,0.180334,67.0,5.0,...,0.255059,até 1000 cc,0.776698,0-100 bhp,10k-30k km,0.019654,0.206644,Renault,0.073531,2017
3487,2017 Honda City i VTEC VX,Dec 2017,1497.0,0.445408,Manual,39000.0,0.150465,0.180334,117.3,5.0,...,0.364786,até 2000 cc,0.126137,100-200 bhp,10k-30k km,0.019654,0.446040,Honda,0.073531,2017
3488,2016 Honda Jazz 1.2 V i VTEC,Jun 2016,1199.0,0.445408,Manual,33000.0,0.150465,0.180334,88.7,5.0,...,0.364786,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644,Honda,0.073531,2016
3489,2017 Maruti Swift VXI,Mar 2017,1197.0,0.445408,Manual,14097.0,0.620328,0.180334,88.5,5.0,...,0.364786,até 2000 cc,0.126137,0-100 bhp,10k-30k km,0.019654,0.206644,Maruti,0.073531,2017

In [75]:
# Contar a quantidade de NaN em cada coluna do DataFrame X
nan_count = df.isna().sum()

# Exibir a contagem de NaN por coluna
print(nan_count)

full_name                    0
registered_year             15
engine_capacity              5
insurance                    0
transmission_type            0
kms_driven                   0
owner_type                   0
fuel_type                    0
max_power                   13
seats                        0
mileage                      0
body_type                    0
city                         0
ID                           0
kms_group                    0
id_kms_group                 0
engine_capacity_group        5
id_engine_capacity_group     0
max_power_group             13
mileage_group                0
id_mileage_group             0
id_max_power_group           0
marca                        0
id_categoria_marca           0
ano                          0
dtype: int64

In [76]:
df = df.astype({
    
    'ano': float,
    'body_type': float,
    
  
})

In [77]:
#Export
#Not the target
colunas_selecionadas = ['body_type','id_categoria_marca','ano','city','insurance','seats','id_mileage_group','id_engine_capacity_group','fuel_type','id_kms_group','id_max_power_group','owner_type','ID']

if set(colunas_selecionadas).issubset(df.columns):
    df_selecionado = df[colunas_selecionadas]
    df_selecionado.to_csv('testcenario2Mileage.csv', index=False)

In [78]:
df_colunas_selecionadas = pd.DataFrame(colunas_selecionadas)

# Contar a quantidade de NaN em cada coluna do DataFrame df_colunas_selecionadas
nan_count = df_colunas_selecionadas.isna().sum()

# Exibir a contagem de NaN por coluna
print(nan_count)

0    0
dtype: int64